<?php

namespace Database\Seeders;

use App\Models\Ruangan;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RuanganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        $data = [
            ['kode' => 'RJ402', 'nama' => 'AKUPUNTUR, SPES LT.4'],
            ['kode' => 'RJ121', 'nama' => 'ANAK LT.1 KM 9'],
            ['kode' => 'RIN01', 'nama' => 'ANGGREK, RANAP'],
            ['kode' => 'RJ105', 'nama' => 'BAYI SEHAT KM.11'],
            ['kode' => 'RJ137', 'nama' => 'BEDAH ANAK KM.8 LT. 1'],
            ['kode' => 'RJ135', 'nama' => 'BEDAH KARDIOVASKULER LT.1 KM 8'],
            ['kode' => 'RJ102', 'nama' => 'BEDAH KM.8 , LT. 1'],
            ['kode' => 'RJ131', 'nama' => 'BEDAH SYARAF LT.1 KM 8'],
            ['kode' => 'RJ130', 'nama' => 'BEDAH TULANG LT.1 KM 8'],
            ['kode' => 'RJ132', 'nama' => 'BEDAH TUMOR LT.1 KM 8'],
            ['kode' => 'RJ124', 'nama' => 'BEDAH UROLOGI LT.1 KM 8'],
            ['kode' => 'DIG01', 'nama' => 'BRONCHOSCOPY'],
            ['kode' => 'RIN14', 'nama' => 'CEMPAKA ISOLASI'],
            ['kode' => 'RJ705', 'nama' => 'DALAM,KONSUL DIABETES LT.7'],
            ['kode' => 'RJ103', 'nama' => 'DIABETES, KLINIK LT.1'],
            ['kode' => 'RIN17', 'nama' => 'DIABETES, RANAP'],
            ['kode' => 'RJ708', 'nama' => 'DIABETES, SPES LT.7'],
            ['kode' => 'DT001', 'nama' => 'DRIVE THRU'],
            ['kode' => 'RAD12', 'nama' => 'ECHOCARDIOGRAFI LT.3'],
            ['kode' => 'RAD07', 'nama' => 'EEG GRAHA UTAMA, LT.4'],
            ['kode' => 'RAD08', 'nama' => 'EMG LT.4'],
            ['kode' => 'DIG02', 'nama' => 'ENDOSCOPY'],
            ['kode' => 'RJ104', 'nama' => 'GIGI & MULUT KM.2 LT.1'],
            ['kode' => 'RJ701', 'nama' => 'GIGI & MULUT, SPES LT.7'],
            ['kode' => 'RJ136', 'nama' => 'GINJAL & HIPERTENSI KM 9'],
            ['kode' => 'RJ115', 'nama' => 'GIZI, KLINIK LT. 1'],
            ['kode' => 'RIN02', 'nama' => 'GLADIOLA'],
            ['kode' => 'RIN27', 'nama' => 'GLADIOLA ISOLASI'],
            ['kode' => 'RIN11', 'nama' => 'GRAHA LT.5'],
            ['kode' => 'RIN12', 'nama' => 'GRAHA LT.6 (WIJAYA KUSUMA)'],
            ['kode' => 'RJ106', 'nama' => 'HATI & PENCERNAAN,LT.1'],
            ['kode' => 'RIN10', 'nama' => 'HATI, RANAP'],
            ['kode' => 'RIN26', 'nama' => 'HEART CENTER & BRAIN SPINE CTR'],
            ['kode' => 'HMD01', 'nama' => 'HEMODIALISA'],
            ['kode' => 'HM001', 'nama' => 'HOME CARE'],
            ['kode' => 'ICU02', 'nama' => 'ICCU'],
            ['kode' => 'ICU01', 'nama' => 'ICU'],
            ['kode' => 'ICU04', 'nama' => 'ICU ANAK'],
            ['kode' => 'ICU05', 'nama' => 'ICU ANGGREK'],
            ['kode' => 'RJ119', 'nama' => 'JANTUNG & P DARAH LT.1 KM 12'],
            ['kode' => 'RJ706', 'nama' => 'JANTUNG & PEMBULUH DARAH, LT.7'],
            ['kode' => 'IBD06', 'nama' => 'JANTUNG RAWAT JALAN'],
            ['kode' => 'RIN09', 'nama' => 'JANTUNG, RANAP'],
            ['kode' => 'RIN24', 'nama' => 'KAMAR BERSALIN GRAHA 5'],
            ['kode' => 'RIN28', 'nama' => 'KAMAR BERSALIN HATI'],
            ['kode' => 'RIN25', 'nama' => 'KAMAR BERSALIN SOKA'],
            ['kode' => 'RJ120', 'nama' => 'KEBIDANAN & KANDUNGAN LT.1 KM6'],
            ['kode' => 'RJ702', 'nama' => 'KEBIDANAN & KANDUNGAN, LT.7'],
            ['kode' => 'RJ107', 'nama' => 'KEBIDANAN KM.6'],
            ['kode' => 'RJ407', 'nama' => 'KEBIDANAN, LT.4'],
            ['kode' => 'RJ101', 'nama' => 'KESEHATAN ANAK KM.9'],
            ['kode' => 'RJ416', 'nama' => 'KLINIK ANAK LT 3'],
            ['kode' => 'RJ415', 'nama' => 'KLINIK BEDAH LT 4'],
            ['kode' => 'RJ418', 'nama' => 'KLINIK DIABETES LT 4'],
            ['kode' => 'RJ419', 'nama' => 'KLINIK GERIATRIC LT.4'],
            ['kode' => 'RJ413', 'nama' => 'KLINIK HATI LT 4'],
            ['kode' => 'RJ417', 'nama' => 'KLINIK IMUNISASI LT 4'],
            ['kode' => 'RJ412', 'nama' => 'KLINIK JANTUNG DAN P.D LT 4'],
            ['kode' => 'RJ414', 'nama' => 'KLINIK KEBIDANAN DAN KAND LT 3'],
            ['kode' => 'RJ411', 'nama' => 'KLINIK KULIT DAN KELAMIN LT 4'],
            ['kode' => 'RJ114', 'nama' => 'KLINIK SUNTIK KM.7'],
            ['kode' => 'RJ134', 'nama' => 'KLINIK SUNTIK LT.4'],
            ['kode' => 'RJ110', 'nama' => 'KLINIK UMUM 1 KM.10 (THT)'],
            ['kode' => 'RJ109', 'nama' => 'KLINIK UMUM 1 KM.3 (PARU)'],
            ['kode' => 'RJ111', 'nama' => 'KLINIK UMUM 2 KM.1 (P. DALAM)'],
            ['kode' => 'RJ410', 'nama' => 'KLINIK UMUM LT 4'],
            ['kode' => 'RJ409', 'nama' => 'KLINIK UMUM, LT.2 (THT)'],
            ['kode' => 'RJ408', 'nama' => 'KLINIK UMUM, LT.4 (P. DALAM)'],
            ['kode' => 'RJ001', 'nama' => 'KPBA'],
            ['kode' => 'RJ108', 'nama' => 'KULIT & KELAMIN KM.5'],
            ['kode' => 'RJ401', 'nama' => 'MATA, SPES LT.4'],
            ['kode' => 'RJ703', 'nama' => 'MATA, SPES LT.7'],
            ['kode' => 'RIN04', 'nama' => 'MAWAR-MELATI'],
            ['kode' => 'RIN03', 'nama' => 'MAWAR-MELATI (X)'],
            ['kode' => 'IBD05', 'nama' => 'MPK RAWAT JALAN'],
            ['kode' => 'RIN18', 'nama' => 'MPK, RANAP'],
            ['kode' => 'RIN23', 'nama' => 'NUSA INDAH , RANAP'],
            ['kode' => 'RIN13', 'nama' => 'NUSA INDAH II, RANAP'],
            ['kode' => 'DAF01', 'nama' => 'PENDAFTARAN'],
            ['kode' => 'RJ118', 'nama' => 'PENYAKIT DALAM LT.1 KM2'],
            ['kode' => 'RJ704', 'nama' => 'PENYAKIT DALAM, SPES LT.7'],
            ['kode' => 'RIN21', 'nama' => 'PERINA , RANAP'],
            ['kode' => 'RJ117', 'nama' => 'POLI GIGI'],
            ['kode' => 'RJ116', 'nama' => 'POLI MATA'],
            ['kode' => 'RJ133', 'nama' => 'POLI THT KM.10'],
            ['kode' => 'RJ123', 'nama' => 'PSIKIATRI LT.1 KM 12'],
            ['kode' => 'RIN07', 'nama' => 'PUTRA I, RANAP'],
            ['kode' => 'RIN20', 'nama' => 'PUTRA III, RANAP'],
            ['kode' => 'RIN29', 'nama' => 'RAWAT INAP ISOLASI'],
            ['kode' => 'RJ403', 'nama' => 'REHABILITASI MEDIK, SPES LT.4'],
            ['kode' => 'RM001', 'nama' => 'REKAM MEDIS'],
            ['kode' => 'RM002', 'nama' => 'REKAM MEDIS (TRANSIT)'],
            ['kode' => 'RIN06', 'nama' => 'SOKA, RANAP'],
            ['kode' => 'RIN08', 'nama' => 'STROKE, RANAP'],
            ['kode' => 'RJ122', 'nama' => 'SYARAF LT.1 KM 7'],
            ['kode' => 'RJ406', 'nama' => 'SYARAF, SPES LT. 4'],
            ['kode' => 'RJ707', 'nama' => 'SYARAF, SPES LT.7'],
            ['kode' => 'RIN05', 'nama' => 'TERATAI, RANAP'],
            ['kode' => 'RJ404', 'nama' => 'THT, SPES LT.4'],
            ['kode' => 'MCU02', 'nama' => 'TREADMILL'],
            ['kode' => 'RJ112', 'nama' => 'UMUM ANAK LT.1'],
            ['kode' => 'RJ113', 'nama' => 'UMUM JANTUNG LT.1'],
            ['kode' => 'RIN16', 'nama' => 'UNIT STROKE, RANAP'],
        ];

        Ruangan::insert($data);
    }
}
